/**
 * verb-hash-table.ts — O(1) verb → templateId lookup.
 *
 * WHAT THIS DOES:
 * ───────────────
 * Loads a pre-generated JSON mapping of verbs (including conjugations)
 * to template IDs. Provides instant O(1) lookup for the Tier 1 pipeline.
 *
 * CONJUGATION STRATEGY:
 * ─────────────────────
 * The hash table is generated by `generate-hash-table.ts`, which uses
 * HAND-ROLLED conjugation rules (not compromise.js). The strategy:
 *
 *   1. IRREGULAR VERBS (90+ entries): Explicit table with all forms.
 *      "swim" → "swims", "swimming", "swam", "swum" (correct)
 *      "run"  → "runs", "running", "ran", "run" (correct)
 *
 *   2. REGULAR VERBS: Suffix rules for 3rd person (-s/-es/-ies),
 *      gerund (-ing with e-drop, consonant doubling), past (-ed/-d/-ied).
 *
 * This approach was chosen over compromise.js conjugation because:
 *   - The hash table is generated OFFLINE (no runtime cost)
 *   - Hand-rolled rules give explicit control over edge cases
 *   - Irregular verb coverage is verifiable (check the table in generate-hash-table.ts)
 *   - A6 (template expansion) can rely on the same conjugation pipeline at scale
 *
 * PERFORMANCE:
 * ────────────
 * Map.get() is O(1). Normalization (lowercase + trim) adds ~0.01ms.
 * Total lookup time: <0.1ms per call.
 */


// ── TYPES ───────────────────────────────────────────────────────────

/** Raw hash table format: { "verb": "template_id", ... } */
export type VerbHashData = Record<string, string>;


// ── VERB HASH TABLE ─────────────────────────────────────────────────

export class VerbHashTable {
    private map = new Map<string, string>();

    /**
     * Create a VerbHashTable from a JSON mapping.
     * @param data - Object mapping verb strings to template IDs
     */
    constructor(data: VerbHashData) {
        for (const [verb, templateId] of Object.entries(data)) {
            this.map.set(verb.toLowerCase().trim(), templateId);
        }
        console.log(`[VerbHashTable] Loaded ${this.map.size} verb entries`);
    }

    /**
     * Look up a verb → templateId. O(1).
     * @param verb - The verb to look up (will be lowercased + trimmed)
     * @returns Template ID or null if not found
     */
    lookup(verb: string): string | null {
        if (!verb) return null;
        return this.map.get(verb.toLowerCase().trim()) ?? null;
    }

    /**
     * Check if a verb exists in the hash table.
     */
    has(verb: string): boolean {
        if (!verb) return false;
        return this.map.has(verb.toLowerCase().trim());
    }

    /**
     * Get the total number of verb entries.
     */
    get size(): number {
        return this.map.size;
    }

    /**
     * Get all verbs mapped to a specific template ID.
     * Useful for debugging and UI display.
     */
    getVerbsForTemplate(templateId: string): string[] {
        const verbs: string[] = [];
        for (const [verb, tid] of this.map) {
            if (tid === templateId) verbs.push(verb);
        }
        return verbs;
    }
}
